services:
  php:
    image: gaetan267/giftbox_image:latest
    container_name: php-container
    ports:
      - "8080:80"
    depends_on:
      - sql

  sql:
    image: mariadb:latest
    container_name: sql-container
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "5080:3306"

  adminer:
    image: adminer:latest
    container_name: adminer-container
    ports:
      - "8081:8080"
    depends_on:
      - sql