services:
  php:
    image: gaetan267/giftbox_image:latest
    container_name: php-container
    ports:
      - "14100:80"
    depends_on:
      - sql

  sql:
    image: mariadb:latest
    container_name: sql-container
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "14101:3306"

  adminer:
    image: adminer:latest
    command:
      - php -S 0.0.0.0:8080 -t /var/www/html
    container_name: adminer-container
    ports:
      - "14102:8080"
    depends_on:
      - sql