networks:
  gift:
    driver: bridge

services:
  php:
    image: canals/php:latest
    container_name: php-container2
    ports:
      - "14100:80"
    depends_on:
      - mariadb
    volumes:
      - ./public:/var/www/html
      - ./src:/var/www/src
    networks:
      - gift

  mariadb:
    image: mariadb:latest
    container_name: mariadb-container
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "14101:3306"
    networks:
      - gift

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-container2
    environment:
      PMA_HOST: mariadb-container
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "14102:80"
    networks:
      - gift